version: '3'

services:
  db:
    image: mariadb
  web:
    build: .
    command: python3 /home/docker/code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/docker/code/
    ports:
      - "8000:8000"
    depends_on:
      - db