version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: livetiming
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./deploy/mariadb/init-data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    build: .
    command: python3 /home/docker/code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/docker/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
    - db