version: '3'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: livetiming
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    links:
     - db
    ports:
     - "80:8000"
    volumes:
     - .:/home/docker/code/
      # Add variables to environment.
    environment:
     - DEBUG=True
     - DB_ENV_NAME=livetiming
     - DB_ENV_USER=admin
     - DB_ENV_PASSWORD=admin
     - DB_ENV_HOST=db
     - DB_ENV_PORT=3306

    command: python3 /home/docker/code/manage.py runserver 0.0.0.0:8000